[package]
name = "cryptex"
version = "1.4.0"
authors = ["Michael Lodder <redmike7@gmail.com>"]
description = """
Cryptex uses system keyrings to store and retrieve secrets
"""
documentation = "https://docs.rs/cryptex/"
license = "Apache-2.0 or MIT"
repository = "https://github.com/mikelodder7/cryptex"
homepage = "https://github.com/mikelodder7/cryptex"
readme = "README.md"
categories = []
keywords = ["secrets", "vault", "keyring"]
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[[bin]]
name = "cryptex"

[features]
default = []

[dependencies]
atty = "0.2"
clap = "2.33"
colored = "2.0"
hex = "0.4"
rand = "0.8"
rpassword = "7"
serde = { version = "1", optional = true }
subtle = "2"
whoami = "1.1"
zeroize = { version = "1", features = ["zeroize_derive"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
users = "0.11"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.6"
security-framework-sys = "2.6"
core-foundation = "0.9"
core-foundation-sys = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
maplit = "1"
secret-service = "2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["dpapi", "errhandlingapi", "wincred", "winerror"] }
byteorder = "1.4"

